# Generated by Django 3.0.2 on 2020-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=500)),
                ('post_image', models.ImageField(upload_to='', verbose_name='image')),
                ('pub_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
    ]
