# Generated by Django 3.0.2 on 2020-02-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200125_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
